project:
  type: website
  output-dir: docs

website:
  title: "Brissa Acevedo"
  navbar:
    left:
      - href: index.qmd
        text: " "
        icon: house-door-fill
      - href: aboutme.qmd
      - href: Camino2PhD.qmd
      - href: Publications.qmd
      
format:
  html:
    theme:
      - journal
      - brand
    css: styles.css
    



