project:
  type: website
  output-dir: docs

website:
  title: "Brissa Acevedo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
      
format:
  html:
    theme:
      - journal
      - brand
    css: styles.css
    



